// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartReminder.Infrastructure.Persistence;

#nullable disable

namespace SmartReminder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartReminderDbContext))]
    partial class SmartReminderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartReminder.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeConvertedToTask")
                        .HasColumnType("bit");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedTaskId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFromLlm")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedTaskId")
                        .IsUnique()
                        .HasFilter("[CreatedTaskId] IS NOT NULL");

                    b.HasIndex("SenderUserId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.PomodoroSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<int>("FocusDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReminderTaskId")
                        .HasColumnType("int");

                    b.Property<int>("ShortBreakMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReminderTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("PomodoroSessions", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ReminderTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuggestedByParentOrTeacher")
                        .HasColumnType("bit");

                    b.Property<int>("MissedCount")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresStudentApproval")
                        .HasColumnType("bit");

                    b.Property<int?>("SourceChatMessageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SourceChatMessageId")
                        .IsUnique()
                        .HasFilter("[SourceChatMessageId] IS NOT NULL");

                    b.ToTable("ReminderTasks", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.StudentParentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreateTasks")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReceiveCriticalAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewMoodNotes")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewProgress")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewVisualSchedule")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId", "ParentId")
                        .IsUnique();

                    b.ToTable("StudentParentLinks", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.StudentTeacherLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreateTasks")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewProgress")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewVisualSchedule")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "TeacherId")
                        .IsUnique();

                    b.ToTable("StudentTeacherLinks", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.TaskStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReminderTaskId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReminderTaskId");

                    b.ToTable("TaskSteps", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.VisualSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StudentId", "ScheduleDate");

                    b.ToTable("VisualSchedules", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.VisualScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedTaskId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisualScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTaskId");

                    b.HasIndex("VisualScheduleId");

                    b.ToTable("VisualScheduleItems", (string)null);
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.ReminderTask", "CreatedTask")
                        .WithOne()
                        .HasForeignKey("SmartReminder.Domain.Entities.ChatMessage", "CreatedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("CreatedTask");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.PomodoroSession", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.ReminderTask", "ReminderTask")
                        .WithMany("PomodoroSessions")
                        .HasForeignKey("ReminderTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "User")
                        .WithMany("PomodoroSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReminderTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ReminderTask", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "OwnerUser")
                        .WithMany("OwnedTasks")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.ChatMessage", "SourceChatMessage")
                        .WithOne()
                        .HasForeignKey("SmartReminder.Domain.Entities.ReminderTask", "SourceChatMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("OwnerUser");

                    b.Navigation("SourceChatMessage");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.StudentParentLink", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.StudentTeacherLink", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.TaskStep", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.ReminderTask", "ReminderTask")
                        .WithMany("Steps")
                        .HasForeignKey("ReminderTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderTask");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.VisualSchedule", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartReminder.Domain.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.VisualScheduleItem", b =>
                {
                    b.HasOne("SmartReminder.Domain.Entities.ReminderTask", "LinkedTask")
                        .WithMany("VisualScheduleItems")
                        .HasForeignKey("LinkedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartReminder.Domain.Entities.VisualSchedule", "VisualSchedule")
                        .WithMany("Items")
                        .HasForeignKey("VisualScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedTask");

                    b.Navigation("VisualSchedule");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("CreatedTasks");

                    b.Navigation("OwnedTasks");

                    b.Navigation("PomodoroSessions");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.ReminderTask", b =>
                {
                    b.Navigation("PomodoroSessions");

                    b.Navigation("Steps");

                    b.Navigation("VisualScheduleItems");
                });

            modelBuilder.Entity("SmartReminder.Domain.Entities.VisualSchedule", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
